name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry update
    - name: Lint with pylint
      run: |
        poetry run pylint redis_rate_limiter
    - name: Check type
      run: |
        poetry run mypy redis_rate_limiter
    - name: Test with pytest
      run: |
        poetry run pytest
